### ISSUE TITLE
_.contains is not there anymore

### ISSUE THREAD

**Issue by AmrAbdulrahman** [mgonto/restangular#1314] opened 2016-02-08 14:18 UTC
Restangular depends on lodash >= 1.3.0
But lodash#4.3.0 has _.contains removed,
this raises TypeError exceptions.

**Comment by bsonntag** [comment] 2016-02-08 17:56
Please fix this.

**Comment by aloker** [comment] 2016-02-10 10:40
+1, I just ran into this issue.

**Comment by AmrAbdulrahman** [comment] 2016-02-10 10:42
there's already an open PR for this: https://github.com/mgonto/restangular/pull/1315

**Comment by DioNNiS** [comment] 2016-02-12 18:47
+1

**Comment by merqlove** [comment] 2016-02-13 12:29
same here

**Comment by ConcurrentHashMap** [comment] 2016-02-15 18:22
Hi @AmrAbdulrahman, thanks for opening up an issue on this. Good news - the issue is finally fixed with the recently released v1.5.2 that addressed this issue. I will close this issue thread now.

Thanks for all of your contributions!

**Closed by ConcurrentHashMap** 2016-02-15 18:22 UTC
