### ISSUE TITLE
returning a status = -1

### ISSUE THREAD

**Issue by sripri** [mgonto/restangular#1398] opened 2016-06-21 22:57 UTC
How do I capture a XHR?  Somehow the error response returned by the rest call gives a status = -1.  I can see the traffic for the first request return a 401 error code. But the subsequent one (looks like it is doing an OPTIONS).  I am aware that CORS needs to be enabled on the server and it is. This is a valid rejection since I am testing with invalid user and password.

> XMLHttpRequest cannot load http://<host>/api/v1.0/login. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4000' is therefore not allowed access. The response had HTTP status code 401.

-----    **_But this is what I am getting as the error response._**

`````` json
{
  "data": null,
  "status": -1,
  "config": {
    "method": "POST",
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "headers": {
      "Authorization": "Basic U1VQRVJVU0VSOkRVUEVS",
      "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json;charset=utf-8"
    },
    "url": "<host>/api/v1.0/login",
    "data": {}
  },
  "statusText": ""
}```
``````

**Comment by sky233** [comment] 2016-08-09 09:55
I also have the same problem.

**Comment by daviesgeek** [comment] 2016-08-31 02:22
It looks like you're missing the `Access-Control-Allow-Origin` header. Regardless of the 401 status code, this header needs to be there for cross-origin requests

**Comment by mnemanja** [comment] 2016-11-14 14:26
@daviesgeek I also have this problem. Why -1? 
The response comes as 200, but my error handler returns with the status -1. What does that mean and why not a known status but this -1?

**Comment by bostrom** [comment] 2016-12-25 19:44
Is the pasted response the raw HTTP response you get from the server? If so, it hasn't been parsed with Restangular yet and thus the problem is not in Restangular but in your server. Please isolate the problem to Restangular and provide a test case if this still persists. I can't find anything in Restangular's source that indicates that the problem is in Restangular. 

Closing this now, but please reopen if you still find that the problem is in Restangular.

**Closed by bostrom** 2016-12-25 19:44 UTC

**Comment by dongtong** [comment] 2017-04-28 07:56
@bostrom 

I have same error, I send  put request, the server does not accept client put request, and client report net::ERR_METHOD_NOT_SUPPORTED, I checked the error, the status is -1.

Thanks

**Comment by ap1969** [comment] 2017-08-26 23:14
Hi,
Did anyone find a solution to this? I'm also getting a -1 on the response.status during the error interceptor. The server is returnging a valid 401 error according to Chrome debugger.
Andy

**Comment by ap1969** [comment] 2017-08-26 23:22
Actually, I've just tested with a simple script posting to http://httpbin.org/status/401 , and I get a response.status of 401.

So, it must be something to do with my server API, although I can't see what. I'll keep plugging away,
