### ISSUE TITLE
Second PUT call sends old data

### ISSUE THREAD

**Issue by miraage** [mgonto/restangular#772] opened 2014-07-02 12:32 UTC
I receive data via `Restangular.all('notices').getList().$object`.
Then I do PUT request on some element - works as expected.
But other PUT requests on this element send old data.

What I do wrong?

**Comment by hartz89** [comment] 2016-03-31 17:14
I was having this issue because I was using angular.copy() to copy an element into scope for editing prior to the PUT rather than using Restangular.copy().  There's a section in the docs about this.

**Comment by daviesgeek** [comment] 2016-03-31 22:19
This sounds like a duplicate of #811. @miraage can you provide an example?

**Comment by daviesgeek** [comment] 2016-06-17 04:27
I'm going to go ahead and close this. @miraage if there's still an issue, feel free to re-open the issue

**Closed by daviesgeek** 2016-06-17 04:27 UTC
Labels: waiting for example

**Comment by miraage** [comment] 2016-06-21 07:36
@daviesgeek i've been figured out this issue by switching `$object` to `then(result => ...)`.
