### ISSUE TITLE
Restangular caches attributes

### ISSUE THREAD

**Issue by daveroberts** [mgonto/restangular#811] opened 2014-08-01 20:54 UTC
I have a save function where I want to change / add properties before save:

``` javascript
$scope.save = function(person){
  person.name = "Overwriting property name";
  person.hobby_ids = [1,2,3];
  person.save();
};
```

Neither the new name, nor the hobby_ids is placed into the PUT request for the person.  At the start of the save function, person did have a name, but not hobby_ids.  The old name was placed into the PUT request.

**Comment by Tzafra** [comment] 2015-04-07 12:19
Still an issue for me - workaround by Restangular.copy on element before saving, but I'd much appreciate a real fix.

**Comment by muenchdo** [comment] 2015-06-22 10:33
In combination with #697 (Cloning sets `fromServer` to `true`) this is a real issue. I can't save my newly created objects because when doing the `Restangular.copy` workaround, Restangular performs a `PUT` request which is rejected by my server. Does anyone know of another workaround? A real fix would also be greatly appreciated.

**Comment by philippeluickx** [comment] 2015-08-18 09:25
I can confirm that by using $object, you can not simply do a put(). It will send the old object. When using the .then(success, failure) approach, everything works fine.

**Comment by akomm** [comment] 2015-11-18 16:02
I'm not sure if that is the same issue. I'm using angular.copy. The copy is modified properly - at least checking via console.log before saving - but the request payload contains old data.

**Comment by hartz89** [comment] 2016-03-31 17:20
@akomm there's a section in the docs about using `angular.copy()`:
https://github.com/mgonto/restangular#copying-elements
> Before modifying an object, we sometimes want to copy it and then modify the copied object. We can't use angular.copy for this because it'll not change the this binded in the functions we add to the object. In this cases, you must use Restangular.copy(fromElement).

**Comment by daviesgeek** [comment] 2016-03-31 22:19
I updated the fiddle (it was using Underscore instead of Lodash).

I can also confirm the bug after playing around with the fiddle. If I have some time, I'll see if I can track down the problem.

http://jsfiddle.net/daviesgeek/qo6wd3Lh/

**Comment by daviesgeek** [comment] 2016-03-31 22:51
Closing as a duplicate of #579. Tracking changes there…

**Closed by daviesgeek** 2016-03-31 22:51 UTC
Labels: bug
