### ISSUE TITLE
Restangular's getList limited to 20 objects on result

### ISSUE THREAD

**Issue by mgnacadj** [mgonto/restangular#1322] opened 2016-02-16 16:10 UTC
Hi everybody! Thanks already for the help and attention on my problems and thanks @mgonto and everybody who worked on restangular for you'r awesome work. It helped me a lot!
Now my problem:
I wanna get a product list from an API made with Django.
Did this: 
    **var Products = Restangular.all('product');
    Products.getList().then(function(list) {
        $scope.prodlist = list;
    });**
And it only gives me 20 objects in result. Even if my product list contains a lot more than that. After research i found it was an issue of synchronisation. I think there is a timeout to put somewhere.
And also i need to fetch a product's data with the name of the product.
Tried this **var Products = Restangular.one('product', {name : "Desperados"});**
and got : 
**the server responded with a status of 500 (INTERNAL SERVER ERROR) http://[ApiAdress]/api/v1/catalog/product/%5Bobject%20Object%5D/[object%20Object]**

Ideas or solutions? :)

**Comment by pedromarce** [comment] 2016-02-16 19:08
Hi @mgnacadj seems strange that rectangular limits the number of results, could you check the network requests in the console, and double check is not your server limiting the number of results? 
Your request for list of products seems correct, but you might have added some default headers or your django api might need a parameter to return all results.
Django has a [pagination](http://www.django-rest-framework.org/api-guide/pagination/#pagination) that might be enabled.

**Comment by mgnacadj** [comment] 2016-02-16 20:40
```
Array[20]
0: Object
1: Object
2: Object
3: Object
4: Object
5: Object
6: Object
7: Object
8: Object
9: Object
10: Object
11: Object
12: Object
13: Object
14: Object
15: Object
16: Object
17: Object
18: Object
19: Object
addRestangularMethod: function () { [native code] }
all: function () { [native code] }
allUrl: function () { [native code] }
clone: function () { [native code] }
customDELETE: function () { [native code] }
customGET: function () { [native code] }
customGETLIST: function () { [native code] }
customOperation: function () { [native code] }
customPOST: function () { [native code] }
customPUT: function () { [native code] }
doDELETE: function () { [native code] }
doGET: function () { [native code] }
doGETLIST: function () { [native code] }
doPOST: function () { [native code] }
doPUT: function () { [native code] }
fromServer: true
get: function () { [native code] }
getList: function () { [native code] }
getRequestedUrl: function () { [native code] }
getRestangularUrl: function () { [native code] }
head: function () { [native code] }
length: 20
metadata: Object
one: function () { [native code] }
oneUrl: function () { [native code] }
options: function () { [native code] }
parentResource: null
patch: function () { [native code] }
plain: function () { [native code] }
post: function () { [native code] }
putElement: function () { [native code] }
remove: function () { [native code] }
reqParams: null
restangularCollection: true
restangularized: true
route: "product"
several: function () { [native code] }
trace: function () { [native code] }
withHttpConfig: function () { [native code] }
__proto__: Array[0]
```

This is the array i get from that request. Tell me if u need some items expanded. The problem is that I don't have dev access to the Django Api since i didn't make it :/

**Comment by pedromarce** [comment] 2016-02-16 20:46
Could you expand the metadata property? Also are you able to open the request outside of restangular and check if you get more than 20 objects there?

**Comment by ConcurrentHashMap** [comment] 2016-02-16 20:46
Could you try to access the API with Postman (a chrome extension) e.g.? I don't think this is a problem with Restangular. We use pagination in the backend at the company I work at too and if no value describing the num of items per page, there is a default value selected.

So to clearly check where the problem is, please double check the API by requesting the same URL with same parameter withs another service. Would like to know the result.

**Comment by mgnacadj** [comment] 2016-02-16 22:34
Will do that tomorrow when i'll get to my workplace. Thanks a lot for the support :)

**Comment by pedromarce** [comment] 2016-02-17 17:35
I am going to assume the issue was the server and close the issue, @mgnacadj reopen it if it is not the case.

**Closed by pedromarce** 2016-02-17 17:35 UTC

**Comment by mgnacadj** [comment] 2016-02-17 17:48
@pedromarce here are the metadata infos:
```
metadata: Object
limit: 20
next: "/api/v1/catalog/product?offset=20&limit=20&main_category=1"
offset: 0
previous: null
total_count: 32
__proto__: Object
```

I can access the API from my browser but i don't know how the url to query the api is formatted. 
I know its not the same URL because:
**http://api.network-concept.bar/admin/** is the url usable with my browser but BaseUrl for restangular is **http://api.network-concept.bar/api/v1/catalog/** and it works.

**Comment by pedromarce** [comment] 2016-02-17 17:52
Hi @mgnacadj, check the response you are receiving, it is limited to 20 (I guess default value) from the server, without knowing your API it will be just a guess, but if you'd like to increase the number of records, you could do:
`var Products = Restangular.all('product');
Products.getList({limit:100}).then(function(list) {
$scope.prodlist = list;
});`

That I think will get you up to 100 results (you had 32 in the specific case), also you could ask if there is a parameter you can send to get all results and pass it same way.

**Comment by mgnacadj** [comment] 2016-02-17 17:55
Okay I was pretty sure i saw that before when i was searching for the reasons i only got 20 objects. Thanks i'm trying the limit parameter on getlist.

**Comment by mgnacadj** [comment] 2016-02-17 18:03
@pedromarce i got the same results as before with this line 
```
Products.getList({main_category:cat.id},{limit:100}).then(function(list) {
            $scope.products = list;
            console.log(list);
 });
```
Still 20 objects. (PS:How can i Re-open the thread? Can't find the way, sorry it my first time on github ^^

**Comment by pedromarce** [comment] 2016-02-17 18:05
You need to add all parameters in same object:

`Products.getList({main_category:cat.id,limit:100}).then(function(list) {
            $scope.products = list;
            console.log(list);
 });`

Could you try this?

**Comment by mgnacadj** [comment] 2016-02-17 18:16
It works! Thanks so much!

**Comment by ConcurrentHashMap** [comment] 2016-02-17 18:18
:+1: Thanks for your feedback!
