### ISSUE TITLE
$object.put() method doesn't work as expected

### ISSUE THREAD

**Issue by AnatoliyLitinskiy** [mgonto/restangular#713] opened 2014-05-15 15:08 UTC
var oneReal = Restangular.one('company',5).get();

// after it will be loaded in controller
$scope.company = oneReal.$object; // {id:5,name:'company 5'}
$scope.company.name = "company 5 edited";
$scope.company.put();
// sends old name 'company 5' not 'company 5 edited'
// Do I have to use method "then(c)" to get loaded object, why I can't use $object that I put in template?

**Comment by picitujeromanov** [comment] 2015-01-27 17:22
this lib is full of dirty bugs and none of them are getting fixed :(

**Comment by magister94** [comment] 2015-02-04 17:26
I'm also running into this problem. 
When I do this:
```
restObj.save().then((response)->
    console.log(response)
)
```
The old version is sent off and `console.log response` shows the unedited original object.
(NOTE: The API responds with the saved object)

@chilly90's fix worked for me.
```
Restangular.copy(restObj).save().then((response) ->
    console.log(response)
)
```
The new correct version is sent of and `console.log(response)` shows the proper new object.

**Comment by michikono** [comment] 2015-02-12 19:27
+1

**Comment by thedig** [comment] 2015-02-12 19:32
Yup, same issue here.

**Comment by maddogawl** [comment] 2015-02-25 20:20
Copy definitely works, is there any traction on an actual fix for this issue?  This had me stuck for quite a while before I found this issue.

**Comment by ADmad** [comment] 2015-02-26 03:12
Given the severity of the issue and lack of action for quite a long time, I wonder if the project is still being actively supported / developed.

Looking at the commit history of master branch I don't see any commit by the original author @mgonto in months. Though I do some see some recent actively on couple of branches by @grabbou.

Would be nice if the community was updated on the status of the project so that just in case the author / contributors of the project are not longer able to maintain it people can move on.

**Comment by grabbou** [comment] 2015-02-26 11:22
@ADmad - I am working with @mgonto to fix all the bugs pretty soon. He's not available at the moment to maintain the project actively as he's giving few talks (e.g. ng-conf). We are in touch all the time having weekly Hangouts so we are pretty on the way to release 1.5 soon.

New release should come out in ~2 weeks with most bugs fixed. We have actually reduced number of opened issues from 180 to around 110 which is a great progress. There are still few PRs waiting to be merged which takes some time as they've been done ages ago so they need some extra loving in order to make them master ready.

**Comment by ADmad** [comment] 2015-02-26 11:31
Thank you for the update @grabbou. The lack of response for this ticket and lull in actively in past few months had me concerned. Great to hear you are picking up the ball and the project is moving ahead.

**Comment by grabbou** [comment] 2015-02-26 11:50
Thanks for bumping this up! The thing is - with so many issues it's quite hard to prioritise them quickly. I do realise we might have missed some serious bugs so Ill pencil down this particular bug on our must-to-fix list as well.

**Comment by jusopi** [comment] 2015-02-26 16:16
Since working w/ Restangular for a while now, I've moved past the fact that the `$object` is not reflecting changes as it should.  Instead I have opted for the more traditional approach of using the parameter passed to the `then` callback like so:
```javascript
Restangular.one( 'foo' ).get().then( function( rsp ){ $scope.foo = rsp; return rsp })
```
This works for both singular resources and resource lists (e.g. `.getList()`).  While it would be nice to have access to `$object`, if you think about using a promise chain, you might not always be working on the same object as `$object`, therefore this isn't as big a deal to me as it once was.

It's good to hear an update will be coming soon though.  Thanks for the good enws @grabbou

**Comment by picitujeromanov** [comment] 2015-02-26 18:14
Good for you. But the rest of us would love to get this bug fixed


Dňa 26 Feb 2015, o 16:16, jusopi <notifications@github.com> napísal:

**Comment by fantasia949** [comment] 2015-02-27 04:02
+1
This bug is so annoying

**Comment by diosney** [comment] 2015-03-03 22:42
+1 Same issue here.

Code below sends the model correctly. Using `$scope.ledger.save()` or `$scope.ledger.put()` directly sends the old value.

```
$scope.submit = function submit() {
        Restangular
          .copy($scope.ledger)
          .save()
          .then(function () {
            growl.success(gettext('Updated successfully.'));
          });
      };

**Comment by ksr583** [comment] 2015-03-10 17:40
I can't even get it working with the .copy technique

**Comment by ElMesa** [comment] 2015-03-13 16:15
**Copy method works in my case. Thanks community :D**

```javascript
Restangular.copy(resourceToUpdate).put();
```

In my scenerio, inspecting with Chrome dev tools i could see r"esourceToUpdate" had the updated info from the ng-model binding just before calling ".put()", but in the network inspector the http request was sending the original data. Copy solved the issue :-/

**Comment by garhbod** [comment] 2015-03-20 04:33
@gonzofish Can I get an example of how you used Restangular.restangularizeElement?

**Comment by garhbod** [comment] 2015-03-20 08:46
Someone with a bit more knowledge might come up with a better solution but my pull request #1091 fixed the problem for me.

Based off @gonzofish .restanularizeElement solution

**Comment by gonzofish** [comment] 2015-03-22 12:03
@garhbod I just do the following before a `.save()`

    restElement = Restangular.restangularizeElement(base, data, urlRoute);
    isFromServer = !!data.fromServer || angular.isDefined(data.id);
    restElement.fromServer = isFromServer;

where (if I was trying to access `/api/people/12`)

     base === my base Url (`/api`)
     data === the data object (which has an `id` field with a value of 12)
     urlRoute === the sub-url I'm trying to get to (`/people`)

I set the `.fromServer` attribute, which let's Restanguar know to do a POST or PUT.

**Comment by garhbod** [comment] 2015-03-23 00:54
Thanks @gonzofish I did work it out in the end.

But your example is very helpful and would be nice to something like it in the documentation.

**Comment by gonzofish** [comment] 2015-04-09 12:50
No problem @garhbod the only problem is that the isServer variable is specific to my data...that is, I _know_ that only the data coming from the server could have an ID field on it...while this is probably common for a lot of projects, it isn't necessarily universal.

**Comment by mmichaelbiz** [comment] 2015-04-11 10:29
@mgonto, do you have any update on if this will be soon fixed? Was it included in the recent versions?

PUT requests are somewhat important... :)

**Comment by bmonty** [comment] 2015-05-19 00:41
+1

**Comment by tgbarker** [comment] 2015-05-28 16:06
+1

**Comment by tomasgarzon** [comment] 2015-06-30 11:04
+1, any news?

**Comment by blaues0cke** [comment] 2015-07-01 09:47
+1, but the using `Restangular.copy` instead of `angular.copy` is a working workaround for me.

**Comment by Fauny** [comment] 2015-07-13 10:53
+1
When to fix?????

**Comment by arthurspa** [comment] 2015-07-20 05:38
+1

**Comment by zhuangya** [comment] 2015-07-20 05:45
i'm unsubscribing this thread.

tired of `+1`s but no solution.

here is my way to wrap RESTful api for angular:
```

return $resource(BACKEND_URL, {parameter: '@parameter'}, {/** custom methods **/})

```

you can build a `factory`, let's say `API`,  return something like: 
```
return {
users: { //assuming you have a api called users like i do
}
};
```.
and i think this is way much easier..

**Comment by picitujeromanov** [comment] 2015-07-20 09:27
Tired of this as well. We switched to restmod instead.

Dňa 20 Jul 2015, o 06:45, Ya Zhuang <notifications@github.com> napísal:

**Comment by zhuangya** [comment] 2015-07-20 09:28
hmm.. looks good to me, worth trying

**Comment by garhbod** [comment] 2015-07-21 05:01
I've created a solution. I don't know why it hasn't being pulled yet

**Comment by arthurspa** [comment] 2015-07-21 11:50
@picitujeromanov, thak you for the suggestion. In few minutes I migrated from restangular, that was with this bug, to restmod and now my app is working fine.

**Comment by picitujeromanov** [comment] 2015-07-21 14:42
You're welcome

Dňa 21 Jul 2015, o 12:50, Arthur Silva <notifications@github.com> napísal:

**Comment by gonzofish** [comment] 2015-07-21 16:31
i'm going back to $http & $q...

**Comment by YannDoW** [comment] 2015-10-12 21:31
I had the same problem. Using:
````
Restangular.copy(resourceToUpdate).save();
````
solved the issue. **Thanks to the community!**

**Comment by quarryman** [comment] 2015-11-09 02:49
Restangular.copy(resourceToUpdate).save() makes PUT request all the time however save should distinguish between POST and PUT

**Comment by simbeto** [comment] 2015-12-05 02:35
looks like project is kind of abandoned! 
This seems to be like an important bug fix.

**Comment by dflourusso** [comment] 2016-01-18 23:56
Restangular v1.5.1

Same problem for me, using `.then()`, it works fine.

**Comment by hartz89** [comment] 2016-03-28 17:27
Hey all,

I discovered that (at least in my case) this is actually not a bug with Restangular.  My problem was that I was using `angular.copy()` instead of `Restangular.copy()` to copy an element into a scope prior to editing it.  I have a feeling many of you may have been doing the same, since this is common (and usually good) practice in Angular.  This IS pointed in the documentation, but I have been missing it up until now...

https://github.com/mgonto/restangular#copying-elements
> Before modifying an object, we sometimes want to copy it and then modify the copied object. We can't use angular.copy for this because it'll not change the this binded in the functions we add to the object. In this cases, you must use Restangular.copy(fromElement).

I hope this helps!

**Comment by daviesgeek** [comment] 2016-03-31 22:51
Closing as a duplicate of #579. Tracking changes there…

**Closed by daviesgeek** 2016-03-31 22:51 UTC
Labels: bug

**Comment by Deleugpn** [comment] 2016-08-19 23:41
Had to settle for the `Restangular.copy(vm.record).save()` solution. Frankly, I don't follow what @hartz89 mean by that last comment, but I know that I just passed the object to a component (`<whatever record="$restangularObject"></whatever>`) and inside that component I have a ng-model pointed to the object.

The interesting thing is that if I `console.log(vm.record)` RIGHT BEFORE `vm.record.save()` I can see the data changed, but the PUT send the wrong data.

**Comment by daviesgeek** [comment] 2016-08-31 03:14
@Deleugpn The comment was pointing out the fact that you need to copy an element using `Restangular.copy` or calling `clone()` on the element in question, not `angular.copy` or something else. Are you copying the object before calling save?

**Comment by Deleugpn** [comment] 2016-08-31 12:54
@daviesgeek I don't understand Angular enough to answer that. All I know is that I pass the object from one Angular Component to another through a scope variable `scope: { object: "=" } `.
