### ISSUE TITLE
TypeError: undefined is not a constructor (evaluating '_.includes(d,a.toLowerCase())

### ISSUE THREAD

**Issue by b0d0nne11** [mgonto/restangular#1323] opened 2016-02-17 01:19 UTC
We started seeing this error in our test coverage yesterday. After a little investigating we determined that it was introduced when we upgraded restangular from v1.5.1 to v1.5.2. We were able to resolve the issue by pinning to v1.5.1 but I wanted to log it here in case anyone else runs into the same thing. I suspect that the lower bound for restangluar's lodash dependency needs to be updated but my NodeJS/Javascript skills aren't nearly good enough to say for sure.

**Comment by ConcurrentHashMap** [comment] 2016-02-17 05:52
Thanks for that. Did you only upgrade Restangular but not lodash? The best would be to upgrade lodash to 3.10.1.

I'm sorry I missed the point that lodash 1 doesn't have _.includes, just .include... 

I will need to correct this today in the evening.

**Comment by pedromarce** [comment] 2016-02-17 17:37
Probably duplicate of #1320, could you check there?

**Closed by pedromarce** 2016-02-17 17:37 UTC

**Comment by b0d0nne11** [comment] 2016-02-17 17:50
@ConcurrentHashMap Correct. I'll see about updating our lodash dep as well but for the time being I just had to get CI working again.

@pedromarce It does look similar but we're not using underscore so the solution provided doesn't work for us. Thanks for pointing this out. I missed it when looking through the open issues yesterday.
