### ISSUE TITLE
lodash has replaced _contains to _includes

### ISSUE THREAD

**Issue by chauhan216** [mgonto/restangular#1307] opened 2016-01-23 15:45 UTC
lodash has replace _contains to _includes in its latest version. This is being used in restangular file so throwing error with undefined function.
        return _.contains(safeMethods, operation.toLowerCase());

**Comment by fabienvauchelles** [comment] 2016-01-24 19:03
+1

**Comment by diegopamio** [comment] 2016-01-25 14:41
+1

**Comment by cayblood** [comment] 2016-01-25 18:49
+1

**Comment by Blackbaud-RobertTester** [comment] 2016-01-25 21:39
+1

**Comment by jeton** [comment] 2016-01-27 10:21
+1

**Comment by Uelb** [comment] 2016-01-28 16:11
+1

**Comment by shepilov-vladislav** [comment] 2016-01-29 15:45
:+1:

**Comment by MRHarrison** [comment] 2016-01-29 19:03
+1

**Comment by Climax777** [comment] 2016-01-30 15:14
Same problem here +1

**Comment by fintis** [comment] 2016-01-31 19:35
+1

**Comment by alimek** [comment] 2016-02-01 10:53
+1

**Comment by pelim** [comment] 2016-02-01 15:43
+1

**Comment by pelim** [comment] 2016-02-01 15:45
why you are not fixing the loaddash version to one implementing ._contains

**Comment by diegopamio** [comment] 2016-02-01 15:50
Because I want to use 4.x version features.

**Comment by spywen** [comment] 2016-02-02 17:01
+1

**Comment by aroucadi** [comment] 2016-02-03 14:03
+1

**Comment by sushantdhiman** [comment] 2016-02-06 07:37
Fix for now in `app.config` phase

 ```
//until https://github.com/mgonto/restangular/issues/1307
 _.contains = _.includes;
```

**Comment by bsonntag** [comment] 2016-02-08 17:57
+1

**Comment by andyk1989** [comment] 2016-02-09 16:16
+1

**Comment by adko-pl** [comment] 2016-02-12 07:49
+1

**Comment by ConcurrentHashMap** [comment] 2016-02-13 16:32
Will be fixed by merging #1314.

**Comment by ConcurrentHashMap** [comment] 2016-02-15 18:20
Good news @chauhan216 and all the others following this thread: The issue is finally fixed. I released v1.5.2 that addresses this issue. I will close this thread for now; feel free to reopen a new issue if something doesn't work as expected.

Thanks for your help and patience!

**Closed by ConcurrentHashMap** 2016-02-15 18:20 UTC
