### ISSUE TITLE
Error : _.contains() is not a function in the latest version of lodash.

### ISSUE THREAD

**Issue by VaibhavP17** [mgonto/restangular#1298] opened 2016-01-15 10:23 UTC
In the latest version(4.0.0) of lodash, _.contais() method is not defined. It was available in version "3.10.0". 
We need to fix the version of lodash the bower.json : 
"lodash": "~3.10.0"
or 
we need to update " _.contains " with " _.includes " . Can we update it ?

**Comment by xeor** [comment] 2016-01-15 12:09
You was 2 hours ahead of me.. I was just about to make the same case.

`contains` used to be an alias to `includes`, and in v4 they removed the alias.

**Comment by mackelito** [comment] 2016-01-15 12:54
I'm also having this issue.. Hope it will be solved soon!

**Comment by Boehner** [comment] 2016-01-15 14:29
+1

**Comment by xeor** [comment] 2016-01-15 14:45
@mgonto @grabbou restangular is broken for new installs.

**Comment by Pompette** [comment] 2016-01-15 15:29
+1

**Comment by dougamos** [comment] 2016-01-15 15:34
+1

**Comment by fmunoz92** [comment] 2016-01-15 18:49
+1

**Comment by evangboucher** [comment] 2016-01-16 21:02
+1

**Comment by wbyoko** [comment] 2016-01-17 03:57
+1

**Comment by tomerf8** [comment] 2016-01-17 10:23
+1

**Comment by DenJohX** [comment] 2016-01-18 05:00
+1

**Comment by xeor** [comment] 2016-01-18 06:41
A simple fix while we wait for someone with commit access is; `sed -i /path/to/restangular/dist/restangular.js -e 's/_\.contains/_\.includes/g'`

**Comment by shvelo** [comment] 2016-01-18 08:52
+1 Please fix ASAP

**Comment by sutkovoy** [comment] 2016-01-18 16:26
+1

**Comment by fmunoz92** [comment] 2016-01-18 16:40
Workaround:
For new installations I used as temporal bower dependency the sssilver fork
"restangular": "https://github.com/sssilver/restangular.git#master"

**Comment by plong0** [comment] 2016-01-18 17:53
If you need a quick workaround before it gets fixed/released and rather than using a fork, you can just update your local project's bower.json dependencies...
`"lodash": "3.10.1"`

Or before installing restangular, use the command
`bower install lodash#3.10.1 --save`

**Comment by pgom** [comment] 2016-01-19 12:17
+1

**Comment by bernardolm** [comment] 2016-01-19 15:07
+1

**Comment by kakulukia** [comment] 2016-01-19 15:27
+1

**Comment by dindras** [comment] 2016-01-19 18:49
+1

**Comment by ulyssesv** [comment] 2016-01-19 19:51
+1

**Comment by xeor** [comment] 2016-01-19 20:00
This is a problem for everyone that installs restangular using bower using the default method. There is no need to +1 this issue. It's a known problem, everyone is having it, and we are waiting for someone with commit permissions to step in. Like @mgonto or @grabbou, which is the last 2 people I found that have done changes.

* There are 2 workarounds that works, use them if you need to temporary.
* Click subscribe to the right if you want to know when someone is commenting on this issue.
* Stop +1 posts. They will send out mails as default to everyone previously commented.
* @ mentioning the owners have sent notifications to them, so they will fix this as soon as they can.

**Comment by dflourusso** [comment] 2016-01-20 17:05
Having the same problem, i created **[THIS](https://github.com/mgonto/restangular/pull/1304)** pull request to solve it. Let's wait the merge now.

**Comment by fabienvauchelles** [comment] 2016-01-24 19:04
+1

**Comment by ivosantiago** [comment] 2016-01-26 22:57
+1 
:+1:

**Comment by grabbou** [comment] 2016-01-28 20:45
Hey. I haven't been in touch with mgonto for a while (I don't have publish permissions) but we could try to fix the most important bits over the weekend and release new version if that works.

Sorry for not responding at all, been pretty crazy year and for some reason I've always skipped these updates :/

**Comment by astephens** [comment] 2016-02-03 22:02
+1

**Comment by zetalei** [comment] 2016-02-04 02:04
+1

**Comment by StevenDewey** [comment] 2016-02-05 20:09
+1

**Comment by ConcurrentHashMap** [comment] 2016-02-15 18:25
Hi @ all, thanks for opening up an issue on this. 

The issue is finally fixed with the recently released v1.5.2.
Thanks to @grabbou who gave me the idea of contacting @mgonto and asking him about fixing this stuff and helping him merging PRs and answering issues! 

Thanks for all of your contributions!

**Closed by ConcurrentHashMap** 2016-02-15 18:25 UTC

**Comment by VaibhavP17** [comment] 2016-02-15 18:29
:+1:

**Comment by bholloway** [comment] 2016-02-16 01:45
The specification in `package.json` still says `>=1.3.1` which is incorrect.

In most cases you will get latest **lodash** which will work, but it projects that have a number of lodash versions **npm** may consolidate to an older version which will then break **restangular**.

**Comment by ConcurrentHashMap** [comment] 2016-02-16 07:34
@bholloway: Yep, you're right. I looked at lodash 1.3 and just saw the "include" function, but missed the missing "s" at the end :see_no_evil: What would you recommend to make it really compatible for everyone? For me that's only setting the lodash version to ^3.10, because this version has "include" as well as "includes" and "contains", so this seems to most compatible version to me at the moment.

**Comment by pedromarce** [comment] 2016-02-16 07:38
Hi, 3.10 seems reasonable to me.

**Comment by achadee** [comment] 2016-02-25 05:25
the most recent version of lodash has all versions

https://github.com/lodash/lodash/blob/a0a649aaeabb0b99300ecb32f80f060f3f39815d/vendor/underscore/underscore.js#L274

**Comment by ConcurrentHashMap** [comment] 2016-02-25 05:42
@achadee no, that's just underscore.js inside the vendor folder of lodash (puh, it gets even more confusing...)
