### ISSUE TITLE
Retry request on 401 error not using restangular objects

### ISSUE THREAD

**Issue by mickael83** [mgonto/restangular#1022] opened 2015-01-30 14:14 UTC
Hi,

With the code below, I am trying to retry a request after getting a fresh access token. The request is correctly executed but the response data is not restangularized. It seems that the response intereceptor does not handle the response when using the $http service.

My response interceptor:

```
          RestangularConfigurer.addResponseInterceptor(function(data) {
            var extractedData;
            extractedData = data.data;
            extractedData.meta = data.meta;
            return extractedData;
          });
```

My error interceptor:

```
    RestangularConfigurer.setErrorInterceptor(function(response, deferred, responseHandler) {
              //console.log(response);
              if(response.status === 401)  {
                refreshToken().then(function (data) {

                  response.config.headers.Authorization = 'Bearer '+ data.access_token;

                  $http(response.config).then(responseHandler, deferred.reject)
                    .then(function (httpResponse) {
                      deferred.resolve(httpResponse); // HERE THE DATA DO NOT PASS TO MY RESPONSE INTERCEPTOR AND CAUSES THE RESPONSE NOT TO BE RESTANGULARIZED
                    });
                });
                return false;
              }
              return true; // error not handled
          });
```

Is it possible to retry the request and resolving the promise with restangularized data?

**Comment by mickael83** [comment] 2015-01-30 14:29
Well it seems that what I am asking is related to the following post:
http://stackoverflow.com/questions/25725896/retry-a-restangular-call-in-an-interceptor

Is there any way to rebuild the  Restangular object simply from the response object config?

**Comment by grabbou** [comment] 2015-02-21 20:18
@mickael83 have you tried `restangularizeElement` method? There are plenty of examples at Google and StackOverflow explaining usages and more powerful solutions.

**Comment by zdavis** [comment] 2015-04-10 19:39
Did you ever find a solution for this? Having the same issue here...

**Comment by devmark** [comment] 2015-06-22 06:30
+1

**Comment by daviesgeek** [comment] 2016-06-17 23:54
The problem is that you're using `$http` to make the request.

>  It seems that the response intereceptor does not handle the response when using the $http service.

Exactly. As @grabbou said, use `restangularizeElement` to fix this issue.

Since there hasn't been any activity on this issue in almost a year, I'm going to go ahead and close it. Feel free to re-open it if it's still an issue for you @mickael83

**Closed by daviesgeek** 2016-06-17 23:54 UTC
Labels: question
