### ISSUE TITLE
add custom restangular method to all collections

### ISSUE THREAD

**Issue by shyam-habarakada** [mgonto/restangular#925] opened 2014-10-28 21:49 UTC
// question 

I'm working with an API that paginates collections. All collection responses take the form

    {
        paging: { page: 1; per_page: 20; prev_page: null; next_page; "..." /* a url */ },
        data: [ /* array of collection items */ ]
    }
 
And I want to implement a new restangular method (similar to `.one`, `.all` etc.) so that something like a `Restangular.allPages('accounts')` call is possible. It would return a promise that resolves when all the pages of data in the collection are fetched. The returned response will be identical to above, except as if an infinite `per_page` value was in effect.

My question is -- what is the best way to extend restangular to get this working? 

The documentation here explains how to extend a specific collection https://github.com/mgonto/restangular#adding-custom-methods-to-collections. But it looks like the custom method will only be available _after_ the `.all` method is called.

**Comment by grabbou** [comment] 2015-02-21 13:09
Duplicate of #719

**Closed by grabbou** 2015-02-21 13:09 UTC
